// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwJjVUZ-Njp0nIT_3568KKS36DF_EQkRM',
    appId: '1:345195233611:web:8cc1f746764db4d1a528ce',
    messagingSenderId: '345195233611',
    projectId: 'tomato-plantation-app',
    authDomain: 'tomato-plantation-app.firebaseapp.com',
    storageBucket: 'tomato-plantation-app.firebasestorage.app',
    measurementId: 'G-Y7ZDT0BLWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE29hH7BhCRvXzLL3jZTyW50YbihPxAJU',
    appId: '1:345195233611:android:73f6573f64b6d921a528ce',
    messagingSenderId: '345195233611',
    projectId: 'tomato-plantation-app',
    storageBucket: 'tomato-plantation-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUW56AXNSWAhuT_19SrjLpS0PMI9OdUI',
    appId: '1:345195233611:ios:f8b254a3a35ff6a0a528ce',
    messagingSenderId: '345195233611',
    projectId: 'tomato-plantation-app',
    storageBucket: 'tomato-plantation-app.firebasestorage.app',
    iosBundleId: 'com.example.tomatoPlantationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgUW56AXNSWAhuT_19SrjLpS0PMI9OdUI',
    appId: '1:345195233611:ios:f8b254a3a35ff6a0a528ce',
    messagingSenderId: '345195233611',
    projectId: 'tomato-plantation-app',
    storageBucket: 'tomato-plantation-app.firebasestorage.app',
    iosBundleId: 'com.example.tomatoPlantationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwJjVUZ-Njp0nIT_3568KKS36DF_EQkRM',
    appId: '1:345195233611:web:1dbf2238adbbb277a528ce',
    messagingSenderId: '345195233611',
    projectId: 'tomato-plantation-app',
    authDomain: 'tomato-plantation-app.firebaseapp.com',
    storageBucket: 'tomato-plantation-app.firebasestorage.app',
    measurementId: 'G-S1M7TW6FMX',
  );
}
